---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - cluster-role.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  # - rotate-tokens.cronjob.yaml

namespace: kanidm-system

commonLabels:
  app.kubernetes.io/component: kanidm-operator
  app.kubernetes.io/instance: kanidm
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: kanidm-operator
  app.kubernetes.io/part-of: kanidm

images:
  - name: kanidm-operator
    newName: sbordeyne/kanidm-operator
    newTag: 1.1.0-beta.13-1
