{% extends "configmap.yaml" %}
{% block component %}server-config{% endblock %}
{% block data %}
    bindaddress = "0.0.0.0:{{ http_port | default(8443) }}"
    ldapbindaddress = "0.0.0.0:{{ ldap_port | default(3630) }}"
    trust_x_forward_for = {{ trust_x_forwarded_for | default(False) | lower }}
    db_path = "/db/kanidm.db"
    db_fs_type = "{{ db_fs_type | default('other') }}"
    {% if db_arc_size %}
    db_arc_size = {{ db_arc_size }}
    {% endif %}
    tls_chain = "/certs/tls.crt"
    tls_key = "/certs/tls.key"
    log_level = "{{ log_level | default('info') }}"
    domain = "{{ domain }}"
    origin = "https://{{ domain }}"
    role = "{{ role | default('WriteReplica') }}"
    {% if backup_enabled %}
    [online_backup]
    path = "/backups/"
    schedule = "{{ backup_schedule | default('0 22 * * *') }}"
    versions = {{ backup_versions | default(7) }}
    {% endif %}
{% endblock %}
