apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kanidms.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: kanidms
    singular: kanidm
    kind: Kanidm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
                - database
                - domain
                - certificate
              properties:
                version:
                  type: string
                  pattern: ^\d+\.\d+\.\d+(-(alpha|beta|rc)\.?\d+)$
                webPort:
                  type: number
                ldapPort:
                  type: number
                database:
                  type: object
                  required:
                    - storageClass
                    - storageSize
                  properties:
                    fsType:
                      type: string
                      enum:
                        - zfs
                        - other
                    arcSize:
                      type: number
                    storageClass:
                      type: string
                    storageSize:
                      type: string
                      pattern: ^\d+[EPTGMK]i?$
                logLevel:
                  type: string
                  enum:
                    - debug
                    - info
                    - warn
                    - error
                    - fatal
                domain:
                  type: string
                certificate:
                  type: object
                  properties:
                    issuer:
                      type: string
                backup:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                      pattern: ^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|Âµs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})$
                    versions:
                      type: number
                    storageClass:
                      type: string
                    storageSize:
                      type: string
                      pattern: ^\d+[EPTGMK]i?$
                highAvailability:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    replicas:
                      type: number
                ingress:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    reverseProxy:
                      type: string
                      enum:
                        - nginx
                        - traefik
                        - caddy
                        - haproxy
                    trustXForwardedFor:
                      type: boolean
